/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6GEmKk9RsZd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function IdeaDetils() {
  return (
    <div className="w-full">
      <img
        alt="Product Image"
        className="w-full h-[400px] md:h-[500px] object-cover"
        height={600}
        src="/placeholder.svg"
        style={{
          aspectRatio: "1200/600",
          objectFit: "cover",
        }}
        width={1200}
      />
      <div className="container mx-auto px-4 md:px-6 py-8 md:py-12 grid md:grid-cols-2 gap-8">
        <div>
          <h1 className="text-3xl md:text-4xl font-bold">Premium Leather Backpack</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            This premium leather backpack is designed for the modern professional. It features a spacious main
            compartment, padded laptop sleeve, and multiple pockets for organization. The durable leather construction
            ensures it will last for years.
          </p>
        </div>
        <div className="flex flex-col items-end gap-4">
          <div className="flex items-center gap-2">
            <Button className="text-green-500 hover:bg-green-100 dark:hover:bg-green-900" size="icon" variant="ghost">
              <ThumbsUpIcon className="w-6 h-6" />
            </Button>
            <span className="text-2xl font-medium">243</span>
            <Button className="text-red-500 hover:bg-red-100 dark:hover:bg-red-900" size="icon" variant="ghost">
              <ThumbsDownIcon className="w-6 h-6" />
            </Button>
            <span className="text-2xl font-medium">18</span>
          </div>
          <div className="border-t pt-4 w-full">
            <h2 className="text-xl font-semibold mb-4">Comments</h2>
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <Avatar className="h-10 w-10">
                  <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium">John Doe</h3>
                    <time className="text-sm text-gray-500 dark:text-gray-400">2 days ago</time>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400 mt-2">
                    This backpack is amazing! It's so well-made and the leather is so soft. I highly recommend it.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <Avatar className="h-10 w-10">
                  <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium">Jane Smith</h3>
                    <time className="text-sm text-gray-500 dark:text-gray-400">1 week ago</time>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400 mt-2">
                    I've been using this backpack for a few months now and it's held up really well. The quality is
                    top-notch.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-span-2 flex justify-end">
          <Button className="text-red-500 hover:bg-red-100 dark:hover:bg-red-900" size="sm" variant="outline">
            <FlagIcon className="w-5 h-5 mr-2" />
            Report
          </Button>
        </div>
      </div>
      <section className="container mx-auto px-4 md:px-6 py-8 md:py-12 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
          <img
            alt="Product Image"
            className="w-full h-[200px] object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="p-4">
            <h3 className="text-lg font-medium">Wireless Headphones</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              High-quality wireless headphones with noise-cancelling technology.
            </p>
            <div className="flex items-center justify-between mt-4">
              <span className="text-2xl font-bold">$99.99</span>
              <Button size="sm" variant="primary">
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
          <img
            alt="Product Image"
            className="w-full h-[200px] object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="p-4">
            <h3 className="text-lg font-medium">Smart Watch</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Stylish and feature-packed smart watch for fitness and productivity.
            </p>
            <div className="flex items-center justify-between mt-4">
              <span className="text-2xl font-bold">$199.99</span>
              <Button size="sm" variant="primary">
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
          <img
            alt="Product Image"
            className="w-full h-[200px] object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="p-4">
            <h3 className="text-lg font-medium">Portable Bluetooth Speaker</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Powerful and portable Bluetooth speaker with long battery life.
            </p>
            <div className="flex items-center justify-between mt-4">
              <span className="text-2xl font-bold">$79.99</span>
              <Button size="sm" variant="primary">
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
          <img
            alt="Product Image"
            className="w-full h-[200px] object-cover"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="p-4">
            <h3 className="text-lg font-medium">Ergonomic Office Chair</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Comfortable and adjustable office chair for long hours of productivity.
            </p>
            <div className="flex items-center justify-between mt-4">
              <span className="text-2xl font-bold">$249.99</span>
              <Button size="sm" variant="primary">
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function ThumbsDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
